[[event]]
path = "20260428-manifestation-palestine"
name = "Manifestation en solidarité du peuple palestinien"
date = 2026-04-28T10:30:00+02:00
place = { name = "Place Jean-Jaurès", addr = "Place Jean-Jaurès, Troyes" }
notes = [
  "Le 30 mars de chaque année est une journée particulière en Palestine et pour tou.te.s les Palestinien.ne.s qu’ils vivent en Palestine, dans les camps de réfugié.e.s ou dans la diaspora dans le monde entier.",
  "C’est la « journée de la terre » commémorée depuis le 30 mars 1976, jour où la police israélienne a tiré sur des Palestiniens qui manifestaient contre la confiscation de leur terre. Bilan 6 morts, des dizaines de blessés et des centaines de personnes incarcérées.",
  "Cette journée de mobilisation est le symbole d’un peuple attaché à sa terre.",
  "Au niveau national un appel à la mobilisation dans les territoires est  impulsé par 90 organisations le 28 mars prochain.",
  "@Collectif aubois pour la paix",
  "https://actionpopulaire.fr/groupes/dffe29a7-2fcb-424e-bb3d-b1d2b4623aaf/",
]

[[event]]
path = "20260428-journee-securite-sante-travail"
name = "Journée internationale de la sécurité et de la santé au travail"
date = 2026-04-28T11:00:00+02:00
place = { name = "Devant le MEDEF", addr = "Place Casimir Perier, Troyes" }
notes = [
  "Il sera suivi par un barbecue fraternel devant le syndicat des cheminots de Troyes (devant la gare).",
  "https://www.cgtud10.fr/actualites/c/0/i/96079644/28-avril-rassemblement-11h-devant-le-medef-stop-aux-morts-au-travail",
]

[[event]]
path = "20260428-presentation-tsedek"
name = "Présentation du livre TSEDEK!"
place = { name = "Maison des syndicats", addr = "2A Boulevard du 1er R.A.M, Troyes" }
date = 2026-04-28T18:30:00+02:00
notes = [
  "Fondé quelques mois avant le 7 octobre 2023, le collectif juif décolonial Tsedek! s'est depuis retrouvé propulsé au cœur des enjeux qui animent le débat politique français, dans un contexte marqué par le génocide à Gaza, la radicalisation autoritaire de l'État et une instrumentalisation toujours plus grande de la lutte contre l'antisémitisme à des fins répressives et racistes.",
  "Dans ce livre, le collectif dresse un premier bilan de deux ans de luttes, et explore les moyens de renouer avec une judéité révolutionnaire et émancipatrice face à la fascisation du monde.",
  "@Collectif Louise Michelle, Tsedek! et les passeurs de textes",
]

[[event]]
path = "20260501-1er-mai"
name = "Manif 1er mai"
place = { name = "Place Jean-Jaurès", addr = "Place Jean-Jaurès, Troyes" }
date = 2026-05-01T10:00:00+02:00
notes = []

[[event]]
path = "20260606-pride"
name = "Pride de Troyes 2026"
place = { name = "Place de la Libération", addr = "Place de la Préfecture 10000 Troyes" }
date = 2026-06-06T14:30:00+02:00
notes = [
  "Des animations toute l'après-midi Cortège militant, Performances d'artistes locaux, Discours, Village Associatif, DJ Set, Buvette, Foodtruck",
  "14:30 Départ",
  "17:30 Arrivée à Sainte-Savine devant l'Art Déco",
  "20:00 After Pride avec Gang Bambi dans l'Art Déco",
  "https://pride2troyes.fr/blog/pride-2026",
]

[[event]]
path = "20260607-printemps-viennes"
name = "Printemps des Viennes"
place = { name = "Place Robert Galley", addr = "Place Robert Galley 10000 Troyes" }
date = 2026-06-07T11:30:00+02:00
notes = ["Le p'tit concert d'onc'Pascal", "Chansons jeunes public"]

[[event]]
path = "20260608-enfantiste"
name = "Rassemblement devant le Tribunal de Troyes @Collectif enfantiste 10"
place = { name = "Tribunal de Troyes", addr = "83 Rue Général de Gaulle, 10000 Troyes" }
date = 2026-06-08T19:00:00+02:00
notes = ["https://www.instagram.com/collectifenfantiste10/p/DZNHRnuMVmJ/"]

[[event]]
path = "20260609-aesh"
name = "Ecole inclusive: toutes et tous mobilisé·es!"
place = { name = "Devant le collège Langevin de Ste Savine", addr = "14 Av. Gabriel Thierry, 10300 Sainte-Savine" }
date = 2026-06-09T17:00:00+02:00
notes = [
  "À la suite du premier groupe de travail sur l’avenir des AESH, une large intersyndicale appelle tous les personnels de l’Éducation nationale à se mobiliser le 9 juin. L’objectif: obtenir la création d’un corps de fonctionnaire pour l’ensemble des AESH, seule condition pour une sortie de la précarité. Pour les associer directement à la définition de leur métier, la FSU-SNUipp lance une consultation nationale.",
  "https://10.snuipp.fr/article/ecole-inclusive-toutes-et-tous-mobilise-es",
]

[[event]]
path = "20260615-enfantiste"
name = "Rassemblement contre les violences faites aux enfants @Collectif enfantiste 10"
place = { name = "Tribunal de Troyes", addr = "83 Rue Général de Gaulle, 10000 Troyes" }
date = 2026-06-15T19:00:00+02:00
notes = [
  "Nous suivons l'appel national à se rassembler partout pour que la loi Intégrale soit votée, le 15 juin à 19h devant les palais de Justice.",
  "Les enfants et les adolescents sont les bienvenus, un espace famille est prévu.",
  "Nous pourrons voir ensemble si nous répétons ce rassemblement !",
  "https://www.instagram.com/collectifenfantiste10/p/DZiZYG9xBMy/",
]

[[event]]
path = "20260620-marche-contre-extreme-droite"
name = "Un coup KO - Rassemblement Contre le racisme, les discriminations et l'extrême droite"
place = { name = "Devant l'hôtel de ville", addr = "Place Alexandre Israël, 10000 Troyes" }
date = 2026-06-20T14:00:00+02:00
notes = [
  "Relai de l'appel à Paris le 21 juin",
  "https://www.humanite.fr/en-debat/antiracisme/le-21-juin-un-coup-ko-contre-le-racisme-toutes-les-discriminations-et-lextreme-droite",
  "@Collectifs aubois de lutte contre les extrêmes droites",
]

[[event]]
path = "20260625-conference-fanny-gallot"
name = "Conférence - Leurs paniques, Nos combats - Par Fanny Gallot"
place = { name = "Espace Monmousseau", addr = "2 Av. du 8 Mai, 10100 Romilly-sur-Seine" }
date = 2026-06-25T18:30:00+02:00
notes = [""]

# [[event]]
# path = ""
# name = ""
# place = { name = "", addr = "" }
# date = false
# notes = [""]
