[[event]]
path = "viewing-parties"
name = "Les Viewing Parties"
place = { name = "Gotham", addr = "17 Rue Pithou, 10000 Troyes" }
date = 2026-07-10T19:30:00+02:00
notes = [
	"!!! HORAIRE INCONNUES !!!",
	"Tout au long de cette programmation estivale, le public pourra retrouver les artistes de la House of Gold: Dear Angel, Galatea Gold, Captain Edward Bitch et bien évidemment Estrella Gold, qui feront de chaque soirée un moment unique de partage, de spectacle et de célébration.",
	"Impossible également de passer à côté de la superbe affiche réalisée par Julie du Gotham. Son travail met parfaitement en lumière l'énergie de l'événement et contribue à faire monter l'impatience avant cette série de rendez-vous estivaux. Un immense bravo à elle pour cette création pleine de caractère et de talent!",
	"Que vous soyez un habitué des Viewing Parties ou que vous souhaitiez découvrir l'univers de la House of Gold pour la première fois, ces soirées s'annoncent comme l'un des événements incontournables de l'été 2026. Entre convivialité, performances et bonne humeur, tous les ingrédients sont réunis pour passer d'excellentes soirées.",
	"Alors notez ces dates dans vos agendas et rendez-vous au Gotham dès le 10 juillet pour célébrer l'été avec la House of Gold!",
	"https://pride2troyes.fr/blog/2026-06-24-viewings-parties-avec-estrella-gold-19",
]

[[event]]
path = "chatons"
name = "Camp CHATONS 2026"
place = { name = "Auberge de Jeunesse Troyes-Rosières", addr = "Chemin Sainte Scholastique 10430 Rosières" }
date = 2026-08-13T14:00:00+02:00
end = 2026-08-17T17:00:00+02:00
notes = [
	"Le camp CHATONS 2026 aura lieu du jeudi 13 août au lundi 17 août à l’auberge de jeunesse Troyes Rosières, Chemin Sainte Scholastique 10430 Rosières (à côté de la ville de Troyes dans l’Aube).",
	"Le camp CHATONS est un moment de convivialité qui rassemble pendant quelques jours les membres du collectif ainsi que des personnes « alliées » qui pourraient apporter leur pierre aux échanges qui s’y dérouleront. Celui-ci doit aussi permettre de profiter du temps ensemble pour parler autant geekerie que vie et avenir du collectif CHATONS.",
	"Pour vous inscrire, merci de compléter le formulaire d’inscription au plus vite même si vous ne maîtrisez pas toutes les informations. Il sera toujours temps de les modifier plus tard.",
	"https://framaforms.org/inscription-au-camp-chatons-2026-1775830691",
	"Le contenu de ce Camp CHATONS est élaboré par les participant⋅es, sur le principe des BarCamp. Ce cadre d’autogestion nous semble important pour mieux appréhender les questionnements autour de la raison d’être du collectif et de son activité. Une fois inscrit⋅e, vous pourrez faire des propositions pour animer des ateliers et prendre connaissance des ateliers proposés par les autres participant⋅es.",
	"https://fr.wikipedia.org/wiki/BarCamp",
	"https://www.chatons.org/node/7600",
]

[[event]]
path = "enfantiste"
name = "Rassemblement contre les violences faites aux enfants @Collectif enfantiste 10"
place = { name = "Tribunal de Troyes", addr = "83 Rue Général de Gaulle, 10000 Troyes" }
date = 2026-09-07T19:00:00+02:00
notes = ["Prochaine mobilisation devant le tribunal pour la «loi intégrale»"]

[[event]]
path = "conference-fanny-gallot"
name = "[REPORTÉ EN SEPTEMBRE] Conférence - Leurs paniques, Nos combats - Par Fanny Gallot"
place = { name = "Espace Monmousseau", addr = "2 Av. du 8 Mai, 10100 Romilly-sur-Seine" }
date = 2026-06-25T18:30:00+02:00
notes = [""]

# [[event]]
# path = ""
# name = ""
# place = { name = "", addr = "" }
# date = false
# notes = [""]
