[[event]]
path = "viewing-parties"
name = "Les Viewing Parties"
place = { name = "Gotham", addr = "17 Rue Pithou, 10000 Troyes" }
date = 2026-07-10T19:30:00+02:00
notes = [
	"!!! HORAIRE INCONNUES !!!",
	"Tout au long de cette programmation estivale, le public pourra retrouver les artistes de la House of Gold: Dear Angel, Galatea Gold, Captain Edward Bitch et bien évidemment Estrella Gold, qui feront de chaque soirée un moment unique de partage, de spectacle et de célébration.",
	"Impossible également de passer à côté de la superbe affiche réalisée par Julie du Gotham. Son travail met parfaitement en lumière l'énergie de l'événement et contribue à faire monter l'impatience avant cette série de rendez-vous estivaux. Un immense bravo à elle pour cette création pleine de caractère et de talent!",
	"Que vous soyez un habitué des Viewing Parties ou que vous souhaitiez découvrir l'univers de la House of Gold pour la première fois, ces soirées s'annoncent comme l'un des événements incontournables de l'été 2026. Entre convivialité, performances et bonne humeur, tous les ingrédients sont réunis pour passer d'excellentes soirées.",
	"Alors notez ces dates dans vos agendas et rendez-vous au Gotham dès le 10 juillet pour célébrer l'été avec la House of Gold!",
	"https://pride2troyes.fr/blog/2026-06-24-viewings-parties-avec-estrella-gold-19",
]

[[event]]
path = "chatons"
name = "Camp CHATONS 2026"
place = { name = "Auberge de Jeunesse Troyes-Rosières", addr = "Chemin Sainte Scholastique 10430 Rosières" }
date = 2026-08-13T14:00:00+02:00
end = 2026-08-17T17:00:00+02:00
notes = [
	"Le camp CHATONS 2026 aura lieu du jeudi 13 août au lundi 17 août à l’auberge de jeunesse Troyes Rosières, Chemin Sainte Scholastique 10430 Rosières (à côté de la ville de Troyes dans l’Aube).",
	"Le camp CHATONS est un moment de convivialité qui rassemble pendant quelques jours les membres du collectif ainsi que des personnes « alliées » qui pourraient apporter leur pierre aux échanges qui s’y dérouleront. Celui-ci doit aussi permettre de profiter du temps ensemble pour parler autant geekerie que vie et avenir du collectif CHATONS.",
	"Pour vous inscrire, merci de compléter le formulaire d’inscription au plus vite même si vous ne maîtrisez pas toutes les informations. Il sera toujours temps de les modifier plus tard.",
	"https://framaforms.org/inscription-au-camp-chatons-2026-1775830691",
	"Le contenu de ce Camp CHATONS est élaboré par les participant⋅es, sur le principe des BarCamp. Ce cadre d’autogestion nous semble important pour mieux appréhender les questionnements autour de la raison d’être du collectif et de son activité. Une fois inscrit⋅e, vous pourrez faire des propositions pour animer des ateliers et prendre connaissance des ateliers proposés par les autres participant⋅es.",
	"https://fr.wikipedia.org/wiki/BarCamp",
	"https://www.chatons.org/node/7600",
]

[[event]]
path = "enfantiste"
name = "Rassemblement contre les violences faites aux enfants @Collectif enfantiste 10"
place = { name = "Tribunal de Troyes", addr = "83 Rue Général de Gaulle, 10000 Troyes" }
date = 2026-09-07T19:00:00+02:00
notes = ["Prochaine mobilisation devant le tribunal pour la «loi intégrale»"]

[[event]]
path = "conference-fanny-gallot"
name = "[REPORTÉ EN SEPTEMBRE] Conférence - Leurs paniques, Nos combats - Par Fanny Gallot"
place = { name = "Espace Monmousseau", addr = "2 Av. du 8 Mai, 10100 Romilly-sur-Seine" }
date = 2026-06-25T18:30:00+02:00
notes = [""]

[[event]]
path = "utopia-survivants-che"
name = "Ciné-débat : Les Survivants du Che"
place = { name = "Cinéma UTOPIA", addr = "11 Rue du Moulinet 10150 Pont-Sainte-Marie" }
date = 2026-09-10T20:00:00+02:00
notes = [
	"Suivi d’un débat animé par la LDH de l’Aube",
	"Après le triomphe de la Révolution cubaine en 1959, trois guérilleros ont suivi Che Guevara dans sa tentative d’étendre le soulèvement au-delà de l’île. En 1967, après leur dernière bataille en Bolivie et l’exécution du Che, ces guerriers de l’ombre se lancent dans un périple extraordinaire de 2 400 km à travers la Bolivie, poursuivis par 4 000 soldats en territoire ennemi dans l’espoir de rejoindre Cuba.",
	"Soixante ans plus tard, les derniers camarades survivants du Che racontent cette histoire inédite, faite d’endurance et de loyauté, dans laquelle les destins individuels ont été façonnés par les grands courants géopolitiques de la Guerre froide. Mêlant des images d’archives rares, des animations et des interviews exclusives, le film fait revivre un chapitre oublié de l’Histoire.",
	"Réalisé par : Christophe Dimitri RÉVEILLE",
	"Année de production : 2026",
	"Pays : France",
	"Durée : 98 minutes",
	"Date de sortie : 09.09.2026",
	"https://site.ldh-france.org/troyes-et-aube/cine-debat-les-survivants-du-che/",
]

[[event]]
path = "france_eternelle_archeologie"
name = "La france éternelle? une enquête archéologique"
place = { name = "Auditorium de St Julien les Villas", addr = "3 Rue Jean Jacques Rousseau, 10800 Saint-Julien-les-Villas" }
date = 2026-09-16T18:30:00+02:00
notes = [
	"Nous ouvrons notre Université Populaire avec la conférence de Jean-Paul DEMOULE qui fut supprimée à cause de la canicule.",
	"Jean-Paul Demoule est l’un des plus grands archéologues français contemporains. Il a interrogé avec rigueur et esprit critique l’idée d’une identité française que certains disent immuable. En analysant 3 millénaires de découvertes archéologiques, il montre que notre histoire est avant tout celle de rencontres, de métissages et de transformations permanentes.",
	"https://www.facebook.com/photo/?fbid=4464951033821158",
]

[[event]]
path = "adelphes"
name = "“Joyeuses Luttes !” - Repas partagé et journée festive aux Adelphes"
place = { name = "Parvis de l’Art Déco à Sainte-Savine", addr = "70 Av. du Général Gallieni, 10300 Sainte-Savine" }
date = 2026-09-20T11:30:00+02:00
end = 2026-09-20T20:00:00+02:00
notes = [
	"🎉 Une journée pour se retrouver, partager… et célébrer nos luttes\u202F!",
	"📅 Dimanche 20 septembre, les Adelphes vous donnent rendez-vous pour une journée placée sous le signe de la joie, de la convivialité et du collectif\u202F!",
	"🍽️ 11h30 — Accueil\u00A0: Venez rencontrer les bénévoles, (re)découvrir notre local et faire connaissance\u202F!",
	"🥗 12h — Repas partagé\u00A0: Ramenez ce qui vous fait plaisir et mettons tout en commun\u202F! Parce qu’un bon moment, ça se partage aussi autour d’une table 💛",
	"🎤 13h — Micro ouvert\u00A0: Un texte à lire\u202F? Une chanson\u202F? Une envie de crier, rire ou partager\u202F? Le micro est à vous\u202F!",
	"💃 14h15 — Atelier danse:\u00A0 Venez danser avec Lola, vous amuser et lâcher prise ensemble\u202F!",
	"🎨 15h — Atelier cyanotype\u00A0: Découvrez cette technique d’impression avec Inès et repartez avec votre création\u202F!",
	"🎶 16h — Chorale féministe\u00A0: On écoute, on chante, on fait raisonner nos voix avec la chorale des Adelphes\u202F!",
	"🎤 17h — Micro ouvert\u00A0: Deuxième chance de prendre le micro et de faire entendre votre voix\u202F!",
	"🎬 18h — Séance cinéma\u00A0: On termine la journée avec la projection de Freaks de Tod Browning.",
	"✨ Et tout au long de l’après-midi\u00A0: expo participative de pancartes de lutte, coin fanzines & surprises\u202F! N’hésite pas à ramener tes pancartes préférées pour les exposer",
	"Alors, venez avec vos pancartes, vos textes, vos idées, vos chansons, votre repas… et surtout votre bonne humeur\u202F!\u00A0🧚‍♀️",
	"https://www.auxadelphes.com/agenda/event-one-f72ey-xbwf4-zbgsy-anzmk-4rxbc-8xt5z-gaesl-chzwc-mgyh5-3x367-dy886-h7bhl-2z559",
]

# [[event]]
# path = ""
# name = ""
# place = { name = "", addr = "" }
# date = false
# notes = [""]
